---
version: '2.1'

# https://docs.docker.com/compose/extends/#understanding-multiple-compose-files

# version: '3'
# extra_hosts:
#  - "cassandra:${CASSANDRA_IP:-localhost}"
#  - "mysql:${MYSQL_IP:-localhost}"
#  - "mariadb:${MARIABD_IP:-localhost}"
#  - "reds:${REDIS_IP:-localhost}"
#  - "webdis:${WEBDIS_IP:-localhost}"
#  - "postgres:${POSTGRES_IP:-localhost}"
#  - "spark:${SPARK_IP:-localhost}"
#  - "hadoop:${HADOOP_IP:-localhost}"
#  - "neo4j:${NEO4J_IP:-localhost}"
#  - "celery:${CELERY_IP:-localhost}"

services:
  data:
    image: tianon/true
    volumes:

    # docker
    - /etc/docker:/etc/docker
    - /var/run/docker.sock:/var/run/docker.sock

    # root dir
    - "./shared/models:/shared/models"
    - "./shared/dicts:/shared/dicts"
    - "./shared/ssl:/shared/ssl"
    - "./shared/www:/var/www"
    - "./shared/html:/var/www/html"
    - "./shared/fake_api:/lwan/wwwroot"

    # etcd
    - "./dockerfiles/data-storage/kvs/etcd/shared/conf.d:/shared/conf.d"
    - "./dockerfiles/data-storage/kvs/etcd/shared/logs:/shared/logs/etcd"
    - "./dockerfiles/data-storage/kvs/etcd/shared/data:/shared/data/etcd"

    # krakend
    - "./dockerfiles/data-aggregation/krakend/shared/conf.d:/shared/conf.d"
    - "./dockerfiles/data-aggregation/krakend/shared/apps:/shared/apps"
    - "./dockerfiles/data-aggregation/krakend/shared/logs:/shared/logs/krakend"

    # crane
    - "./dockerfiles/moby/local/crane/shared/logs:/shared/logs/crane"
    - "./dockerfiles/moby/local/crane/shared/apps:/shared/apps/crane"
    - "./dockerfiles/moby/local/crane/shared/conf.d:/shared/conf.d/crane"

    # crane
    - "./dockerfiles/moby/local/nut/shared/logs:/shared/logs/nut"
    - "./dockerfiles/moby/local/nut/shared/apps:/shared/apps/nut"
    - "./dockerfiles/moby/local/nut/shared/conf.d:/shared/conf.d/nut"

    # aiohttp_admin
    - "./dockerfiles/front-end/admin-interface/aiohttp/admin/shared/dicts:/shared/dicts"
    - "./dockerfiles/front-end/admin-interface/aiohttp/admin/shared/utils:/scripts/utils"
    - "./dockerfiles/front-end/admin-interface/aiohttp/admin/shared/apps:/shared/apps"
    - "./dockerfiles/front-end/admin-interface/aiohttp/admin/shared/logs:/shared/logs/aiohttp_admin"
    - "./dockerfiles/front-end/admin-interface/aiohttp/admin/shared/data:/shared/data/aiohttp_admin"
    - "./dockerfiles/front-end/admin-interface/aiohttp/admin/shared/conf.d:/shared/data/conf.d"

    # mongodb
    - "./dockerfiles/data-storage/nosql/mongodb/shared/logs:/shared/logs/mongodb"
    - "./dockerfiles/data-storage/nosql/mongodb/shared/data:/shared/data/mongodb"
    - "./dockerfiles/data-storage/nosql/mongodb/shared/conf.d:/shared/data/conf.d"

    # mariadb
    - "./dockerfiles/data-storage/sql/mariadb/shared/logs:/shared/logs/mariadb"
    - "./dockerfiles/data-storage/sql/mariadb/shared/data:/shared/data/mariadb"
    - "./dockerfiles/data-storage/sql/mariadb/shared/conf.d:/shared/data/conf.d"

    # mysql
    - "./dockerfiles/data-storage/sql/mysql/shared/logs:/shared/logs/mysql"
    - "./dockerfiles/data-storage/sql/mysql/shared/data:/shared/data/mysql"
    - "./dockerfiles/data-storage/sql/mysql/shared/conf.d:/shared/data/conf.d"

    # postgres
    - "./dockerfiles/data-storage/sql/postgres/shared/logs:/shared/logs/postgres"
    - "./dockerfiles/data-storage/sql/postgres/shared/data:/shared/data/postgres"
    - "./dockerfiles/data-storage/sql/postgres/shared/conf.d:/shared/data/conf.d"

    # redis
    - "./dockerfiles/data-storage/kvs/redis/shared/logs:/shared/logs/redis"
    - "./dockerfiles/data-storage/kvs/redis/shared/data:/shared/data/redis"
    - "./dockerfiles/data-storage/kvs/redis/shared/conf.d:/shared/data/conf.d"

    # webdis
    - "./dockerfiles/restful-api/webdis/shared/logs:/shared/logs/webdis"
    - "./dockerfiles/restful-api/webdis/shared/data:/shared/data/webdis"
    - "./dockerfiles/restful-api/webdis/shared/conf.d:/shared/data/conf.d"

    # nodejs
    - "./dockerfiles/base/nodejs/shared/logs:/shared/logs/nodejs"
    - "./dockerfiles/base/nodejs/shared/data:/shared/data/nodejs"
    - "./dockerfiles/base/nodejs/shared/conf.d:/shared/data/conf.d"

    # sphinx
    - "./dockerfiles/search-engines/sphinx/shared/logs:/shared/logs/sphinx"
    - "./dockerfiles/search-engines/sphinx/shared/data:/shared/data/sphinx"
    - "./dockerfiles/search-engines/sphinx/shared/conf.d:/shared/data/conf.d"

    # gitsome
    - "./dockerfiles/vcs/gitsome/shared/logs:/shared/logs/gitsome"
    - "./dockerfiles/vcs/gitsome/shared/data:/shared/data/gitsome"
    - "./dockerfiles/vcs/gitsome/shared/conf.d:/shared/data/conf.d"

    # sqlmap
    - "./dockerfiles/security/sqlmap/shared/logs:/shared/logs/sqlmap"
    - "./dockerfiles/security/sqlmap/shared/data:/shared/data/sqlmap"
    - "./dockerfiles/security/sqlmap/shared/conf.d:/shared/data/conf.d"

    # setoolkit
    - "./dockerfiles/security/setoolkit/shared/logs:/shared/logs/setoolkit"
    - "./dockerfiles/security/setoolkit/shared/data:/shared/data/setoolkit"
    - "./dockerfiles/security/setoolkit/shared/conf.d:/shared/data/conf.d"

    # celery
    - "./dockerfiles/distributed-tasks/celery/shared/logs:/shared/logs/celery"
    - "./dockerfiles/distributed-tasks/celery/shared/data:/shared/data/celery"
    - "./dockerfiles/distributed-tasks/celery/shared/conf.d:/shared/data/conf.d"

  nginx:
    image: "${DOCKER_HUB_ACCOUNT}/nginx:1.11.3-alpine"
    container_name: nginx-1.11.3
    build:
      context: "./dockerfiles/reverse-proxy/nginx"
      dockerfile: nginx-1.11.3-alpine.dockerfile
    volumes_from:
    - data
    ports:
    - 80:80
    - 443:443
    links:
    - php
    # - golang
    # - nodejs

  etcd:
    image: "${DOCKER_HUB_ACCOUNT}/etcd:${ETCD_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    build:
      context: "./dockerfiles/data-storage/kvs/etcd"
      dockerfile: "etcd.alpine.dockerfile"
    container_name: "etcd-${ETCD_VERSION}"
    volumes_from:
    - data
    ports:
    - 2379:2379
    - 2380:2380
    expose:
    - 2379
    - 2380
    env_file:
    - "./dockerfiles/data-storage/kvs/etcd/etcd.config.env"

  nodejs:
    image: "${DOCKER_HUB_ACCOUNT}/nodejs:${NODEJS_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    build:
      context: "./dockerfiles/base/nodejs"
      dockerfile: "nodejs${NODEJS_VERSION}-alpine.dockerfile"
    container_name: "nodejs-${NODEJS_VERSION}"
    volumes_from:
    - data
    ports:
    - 8000:8000
    expose:
    - 8000
    links:
    - webdis
    - redis
    - postgres
    - mariadb
    - mysql
    - mongodb
    env_file:
    - "./dockerfiles/base/nodejs/nodejs.config.env"

  golang:
    image: "${DOCKER_HUB_ACCOUNT}/golang:${GOLANG_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    build:
      context: "./dockerfiles/base/golang"
      dockerfile: "golang${GOLANG_VERSION}-alpine.dockerfile"
    container_name: "golang-${GOLANG_VERSION}"
    volumes_from:
    - data
    expose:
    - 9000
    links:
    - webdis
    - redis
    - postgres
    - mariadb
    - mysql
    - mongodb
    - sphinx
    env_file:
    - "./dockerfiles/base/golang/golang.config.env"

  php:
    image: "${DOCKER_HUB_ACCOUNT}/php-fpm:7.0-alpine${ALPINE_DEFAULT_VERSION}"
    build:
      context: "./dockerfiles/base/php"
      dockerfile: php-7.0-fpm-alpine.dockerfile
    container_name: php-7.0-fpm
    volumes_from:
    - data
    expose:
    - 9000
    links:
    - webdis
    - redis
    - postgres
    - mariadb
    - mysql
    - mongodb
    - sphinx
    env_file:
    - "./dockerfiles/base/php/php.config.env"

  postgres:
    image: "${DOCKER_HUB_ACCOUNT}/postgres:${POSTGRES_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    build:
      context: "./dockerfiles/data-storage/sql/postgres"
      dockerfile: postgres${POSTGRES_VERSION}-alpine.dockerfile
    container_name: postgres-${POSTGRES_VERSION}
    ports:
    - 5432:5432
    expose:
    - 3306
    volumes_from:
    - data
    env_file:
    - "./dockerfiles/data-storage/sql/postgres/postgres.config.env"

  krakend:
    image: "${DOCKER_HUB_ACCOUNT}/krakend:${KRAKEND_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: krakend-${KRAKEND_VERSION}
    build:
      context: "./dockerfiles/data-aggregation/krakend"
      dockerfile: krakend.alpine.dockerfile
    volumes_from:
    - data
    ports:
    - "8096:8096"
    links:
    - fake_api
    env_file:
    - "./dockerfiles/data-aggregation/krakend/krakend.config.env"

  fake_api:
    image: jaxgeller/lwan
    volumes_from:
    - data
    ports:
    - "8002:8080"

  mysql:
    image: "${DOCKER_HUB_ACCOUNT}/mysql:${MYSQL_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    build:
      context: "./dockerfiles/data-storage/sql/mysql"
      dockerfile: mysql${MYSQL_VERSION}-alpine.dockerfile
    container_name: mysql-${MYSQL_VERSION}
    ports:
    - 3306:3306
    expose:
    - 3306
    volumes_from:
    - data
    env_file:
    - "./dockerfiles/data-storage/sql/mysql/mysql.config.env"

  mariadb:
    image: "${DOCKER_HUB_ACCOUNT}/mariadb:${MARIADB_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: "mariadb-${MARIADB_VERSION}"
    build:
      context: "./dockerfiles/data-storage/sql/mariadb"
      dockerfile: "mariadb${MARIADB_VERSION}-alpine.dockerfile"
    ports:
    - 3307:3306
    expose:
    - 3307
    volumes_from:
    - data
    env_file:
    - "./dockerfiles/data-storage/sql/mariadb/mariadb.config.env"

  celery:
    image: "${DOCKER_HUB_ACCOUNT}/celery:apk${CELERY_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: "celery-${CELERY_VERSION}"
    build:
      context: "./dockerfiles/distributed-tasks/celery"
      dockerfile: celery-alpine.dockerfile
    entrypoint: "/opt/entrypoint.sh"
    env_file:
    - "./dockerfiles/distributed-tasks/celery/celery.config.env"
    volumes_from:
    - data
    links:
    - mysql
    - redis

  memcached:
    image: "${DOCKER_HUB_ACCOUNT}/memcached:${MEMCACHED_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: memcached-${MEMCACHED_VERSION}
    build:
      context: "./dockerfiles/data-storage/kvs/memcached"
      dockerfile: memcached-alpine.dockerfile
    ports:
      - 11211:11211
    expose:
    - 11211
    volumes_from:
    - data
    env_file:
    - "./dockerfiles/data-storage/kvs/memcached/memcached.config.env"

  neo4j:
    container_name: neo4j
    #image: neo4j:3.2
    image: "${DOCKER_HUB_ACCOUNT}/neo4j:${NEO4J_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    build:
      context: "./dockerfiles/data-storage/graph/neo4j"
      dockerfile: neo4j.alpine.dockerfile
    ports:
      - 7474:7474
      - 7687:7687
      - 7473:7473
    expose:
    - 7474
    - 7687
    - 7473
    volumes_from:
    - data
    # - ./vms/neo4j/data:/data
    # - ./vms/neo4j/logs:/logs
    # - ./vms/neo4j/conf:/conf
    env_file:
    - "./dockerfiles/data-storage/graph/neo4j/neo4j.config.env"

  aiohttp_admin:
    image: "${DOCKER_HUB_ACCOUNT}/aiohttp_admin-${AIOHTTP_ADMIN_VERSION}:py3.6-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: aiohttp-admin-${AIOHTTP_ADMIN_VERSION}
    build:
      context: "./dockerfiles/front-end/admin-interface/aiohttp/admin"
      dockerfile: aiohttp_admin.alpine.dockerfile
    command: dev
    ports:
    - 9001:9001
    expose:
    - 9001
    depends_on:
    - webdis
    - redis
    - postgres
    - mysql
    - mongodb
    links:
    - webdis
    - redis
    - postgres
    - mysql
    - mongodb
    volumes_from:
    - data
    volumes:
    - "./dockerfiles/front-end/admin-interface/aiohttp/admin/shared/apps:/shared/apps"
    - "./dockerfiles/front-end/admin-interface/aiohttp/admin/shared/logs:/shared/logs/aiohttp_admin"
    - "./dockerfiles/front-end/admin-interface/aiohttp/admin/shared/data:/shared/data/aiohttp_admin"
    - "./dockerfiles/front-end/admin-interface/aiohttp/admin/shared/conf.d:/shared/data/conf.d"
    env_file:
    - "./dockerfiles/front-end/admin-interface/aiohttp/admin/aiohttp_admin.config.env"

  mongodb:
    image: "${DOCKER_HUB_ACCOUNT}/mongo:${MONGODB_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: "mongodb-${MONGODB_VERSION}"
    build:
      context: "./dockerfiles/data-storage/nosql/mongodb"
      dockerfile: mongodb-alpine.dockerfile
    ports:
    - 27017:27017
    - 27018:27018
    - 27019:27019
    - 28017:28017
    expose:
    - 27017
    - 27018
    - 27019
    - 28017
    volumes_from:
    - data
    env_file:
    - "./dockerfiles/data-storage/nosql/mongodb/mongodb.config.env"
    entrypoint:
    - mongod
    command:
    - "--smallfiles"
    - "--dbpath"
    - "/shared/data/mongodb"

  gitsome:
    image: "${DOCKER_HUB_ACCOUNT}/gitsome:${GITSOME_VERSION}-py3.5-alpine3.4"
    container_name: "gitsome-${GITSOME_VERSION}"
    build:
      context: "./dockerfiles/vcs/managers/gitsome"
      dockerfile: gitsome.alpine.dockerfile
    volumes_from:
    - data
    env_file:
    - "./dockerfiles/vcs/managers/gitsome/gitsome.config.env"
    command:
    - dev

  searx:
    image: ${DOCKER_HUB_ACCOUNT}/searx:latest-alpine${ALPINE_DEFAULT_VERSION}
    container_name: searx
    build:
      context: "./dockerfiles/data-aggregation/searx"
      dockerfile: "searx.alpine.dockerfile"
    ports:
    - 8888:8888
    - 8889:8889
    # - 80:80/tcp
    # - 443:443/tcp
    expose:
    - 8888
    - 8889
    volumes_from:
    - data
    env_file:
    - "./dockerfiles/data-aggregation/searx/searx.config.env"
    command:
    - dev

  redis:
    image: "${DOCKER_HUB_ACCOUNT}/redis:${REDIS_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: redis-${REDIS_VERSION}
    build:
      context: "./dockerfiles/data-storage/kvs/redis"
      dockerfile: redis${REDIS_VERSION}-alpine.dockerfile
    ports:
    - 6379:6379
    expose:
    - 6379
    volumes_from:
    - data
    env_file:
    - "./dockerfiles/data-storage/kvs/redis/redis.config.env"

  webdis:
    image: "${DOCKER_HUB_ACCOUNT}/webdis:latest-${WEBDIS_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: webdis-${WEBDIS_VERSION}
    build:
      context: "./dockerfiles/restful-api/webdis"
      dockerfile: webdis-alpine.dockerfile
    ports:
    - 7379:7379
    expose:
    - 7379
    volumes_from:
    - data
    env_file:
    - "./dockerfiles/restful-api/webdis/webdis.config.env"

  sphinx:
    image: "${DOCKER_HUB_ACCOUNT}/sphinx:${SPHINX_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: sphinx-${SPHINX_VERSION}
    build:
      context: "./dockerfiles/search-engines/sphinx"
      dockerfile: sphinx.alpine.dockerfile
    volumes_from:
    - data
    links:
    - mariadb
    - mysql
    - postgres
    depends_on:
    - mariadb
    - mysql
    - postgres
    ports:
    - 9306:9306
    expose:
    - 9306
    env_file:
    - "./dockerfiles/search-engines/sphinx/sphinx.config.env"

  gogs:
    # image: "${DOCKER_HUB_ACCOUNT}/gogs:${GOGS_VERSION}-py${GOGS_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    image: bhuisgen/alpine-gogs
    build:
      context: "./dockerfiles/vcs/managers/gogs"
      dockerfile: gogs.alpine.dockerfile
    ports:
      - "3000:3000"
      - "2222:22"
    volumes_from:
    - data
    volumes:
      - /etc/localtime:/etc/localtime:ro
    #    #- /srv/data:/var/lib/gogs
    env_file:
    - "./dockerfiles/vcs/managers/gogs/gogs.config.env"

  setoolkit:
    image: "${DOCKER_HUB_ACCOUNT}/setoolkit:${SETOOLKIT_VERSION}-py${SETOOLKIT_PY_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: "setoolkit-${SETOOLKIT_VERSION}"
    build:
      context: "./dockerfiles/security-analysis/setoolkit"
      dockerfile: setoolkit.alpine.dockerfile
    volumes_from:
    - data
    env_file:
    - "./dockerfiles/security-analysis/setoolkit/setoolkit.config.env"

  sqlmap:
    image: "${DOCKER_HUB_ACCOUNT}/sqlmap:${SQLMAP_VERSION}-py${SQLMAP_PY_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: sqlmap-${SQLMAP_VERSION}
    build:
      context: "./dockerfiles/security-analysis/sqlmap"
      dockerfile: sqlmap.alpine.dockerfile
    volumes_from:
    - data
    env_file:
    - "./dockerfiles/security-analysis/sqlmap/sqlmap.config.env"

  crane:
    image: "${DOCKER_HUB_ACCOUNT}/crane:${CRANE_VERSION}-go${ALPINE_GOLANG_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: crane-${SQLMAP_VERSION}
    build:
      context: "./dockerfiles/moby/local/crane"
      dockerfile: crane.alpine.dockerfile
    volumes_from:
    - data
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - DOCKER_SOCKET
    env_file:
    - "./dockerfiles/moby/local/crane/crane.config.env"
    entrypoint: /usr/local/sbin/crane
    command: ["--help"]

  nut:
    image: "${DOCKER_HUB_ACCOUNT}/crane:${NUT_VERSION}-go${ALPINE_GOLANG_VERSION}-alpine${ALPINE_DEFAULT_VERSION}"
    container_name: crane-${SQLMAP_VERSION}
    build:
      context: "./dockerfiles/moby/image/nut"
      dockerfile: nut.alpine.dockerfile
      # dockerfile: nut-release.alpine.dockerfile
      # dockerfile: nut-source.alpine.dockerfile
    volumes_from:
    - data
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - DOCKER_SOCKET
    env_file:
    - "./dockerfiles/moby/image/nut/nut.config.env"
    entrypoint: nut
    command: ["--help"]

